name: PR Review Bot
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install and Start Ollama
        run: |
          # Install Ollama
          curl -L https://ollama.ai/install.sh | sh
          
          # Start Ollama in background with output logging
          nohup ollama serve > ollama.log 2>&1 &
          
          # Store the PID
          echo $! > ollama.pid
          
          # Wait for Ollama to be ready
          echo "Waiting for Ollama to be ready..."
          timeout 180s bash -c '
            while ! curl -sf http://localhost:11434/ >/dev/null 2>&1; do
              echo "Waiting for Ollama... $(date)"
              sleep 5
            done
          '
          
          # Pull the model
          echo "Pulling CodeLlama model..."
          ollama pull codellama
          
          # Verify model is available
          echo "Verifying model..."
          ollama list | grep codellama
          
          # Keep Ollama running for subsequent steps
          disown $(cat ollama.pid)
      
      - name: PR Review
        uses: actions/github-script@v7
        with:
          script: |
            const util = require('util');
            const exec = util.promisify(require('child_process').exec);
            const prNumber = context.payload.pull_request.number;
            const repo = context.repo;
            
            async function generateReview(prompt) {
              const { stdout } = await exec(`curl -m 300 -X POST http://localhost:11434/api/generate -d '{
                "model": "codellama",
                "prompt": ${JSON.stringify(prompt)},
                "stream": false
              }'`, { maxBuffer: 10 * 1024 * 1024 });
              
              return JSON.parse(stdout).response;
            }
            
            // Main review process
            async function reviewPR() {
              try {
                // Test Ollama is responding
                await exec('curl -sf http://localhost:11434/');
              } catch (error) {
                console.error('Ollama is not responding:', error);
                throw new Error('Ollama service is not available');
              }
              
              // Get the PR diff
              const { data: files } = await github.rest.pulls.listFiles({
                ...repo,
                pull_number: prNumber,
              });
              
              // Get PR details
              const { data: pullRequest } = await github.rest.pulls.get({
                ...repo,
                pull_number: prNumber,
              });
              
              for (const file of files) {
                try {
                  // Get file content
                  const { data: fileContent } = await github.rest.repos.getContent({
                    ...repo,
                    path: file.filename,
                    ref: pullRequest.head.sha,
                  });
                  
                  const content = Buffer.from(fileContent.content, 'base64').toString();
                  
                  // Prepare prompt
                  const prompt = `Review this code change and provide specific, actionable feedback:
                  File: ${file.filename}
                  Changes:
                  ${file.patch}
                  Please analyze for:
                  1. Potential bugs
                  2. Security issues
                  3. Performance improvements
                  4. Code style and best practices
                  5. Documentation needs
                  Provide specific, line-by-line feedback where applicable.`;
                  
                  // Generate review
                  const review = await generateReview(prompt);
                  
                  // Post review comment
                  await github.rest.pulls.createReviewComment({
                    ...repo,
                    pull_number: prNumber,
                    body: review,
                    commit_id: context.payload.pull_request.head.sha,
                    path: file.filename,
                    line: file.patch ? file.patch.split('\n').length : 1
                  });
                } catch (error) {
                  console.error(`Error processing file ${file.filename}:`, error);
                  continue;
                }
              }
            }
            
            // Run the review
            await reviewPR().catch(error => {
              console.error('Error in PR review process:', error);
              core.setFailed(error.message);
            });
