name: PR Review Bot
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Run PR Review
        env:
          API_KEY: ${{ secrets.REVIEW_API_KEY }}
          API_ENDPOINT: ${{ secrets.REVIEW_API_ENDPOINT }}
        uses: actions/github-script@v7
        with:
          script: |
            const { reviewPR } = require('./.github/scripts/api-review.js');
            await reviewPR({ github, context, core });