name: PR Review Bot
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Ollama
        run: |
          echo "::group::Installing Ollama"
          curl -fsSL https://ollama.com/install.sh | sh
          echo "Ollama version:"
          ollama --version
          echo "::endgroup::"
        
      - name: Pull Deepseek Model
        id: model-pull
        run: |
          echo "::group::Pulling Deepseek Model"
          start_time=$(date +%s)
          echo "Starting model pull at $(date)"
          
          # Start Ollama service
          ollama serve &
          
          # Wait for service to be ready
          echo "Waiting for Ollama service to start..."
          sleep 30
          
          # Pull the model with a timeout of 10 minutes
          timeout 600 ollama pull deepseek-coder:33b
          
          # Verify model is ready
          echo "Verifying model setup..."
          ollama list | grep deepseek-coder:33b
          
          end_time=$(date +%s)
          duration=$((end_time - start_time))
          echo "Model pull completed in ${duration} seconds"
          echo "::endgroup::"
          
          # Additional wait time to ensure model is fully loaded
          echo "Allowing additional time for model initialization..."
          sleep 60
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Run PR Review
        uses: actions/github-script@v7
        with:
          script: |
            const { reviewPR } = require('./.github/scripts/pr-review.js');
            await reviewPR({ github, context, core });