name: PR Review Bot
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Ollama
        run: |
          echo "::group::Installing Ollama"
          curl -fsSL https://ollama.com/install.sh | sh
          echo "Ollama version:"
          ollama --version
          echo "::endgroup::"
        
      - name: Pull Deepseek Model
        id: model-pull
        run: |
          echo "::group::Pulling Deepseek Model"
          # Start Ollama service
          ollama serve &
          
          # Wait for service to be ready
          sleep 30
          
          # Pull the model with a timeout of 10 minutes
          timeout 600 ollama pull deepseek-coder:33b
          
          # Verify and wait for model
          ollama list | grep deepseek-coder:33b
          sleep 60
          echo "::endgroup::"
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Run PR Review
        uses: actions/github-script@v7
        with:
          script: |
            const { reviewPR } = require('./.github/scripts/pr-review.js');
            await reviewPR({ github, context, core });